import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import { headers } from "next/headers";
import Sidebar from "@/components/layout/Sidebar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children }) {
  const headersList = headers();
  const url = headersList.get('next-url')
  const session = await getServerSession(authOptions);
  
  if (!session) {
    return redirect('/');
  }


  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <main className="flex min-h-screen">
          <aside className="bg-gray-50 w-48 p-4 pt-8 shadow">
            <div className="rounded-full overflow-hidden w-24 h-24 mx-auto">
              <Image src={session.user.image} alt="avatar" width={256} height={256} className="aspect-square object-cover" />
            </div>
            <div className="text-center">
              <Sidebar />
            </div>
            
          </aside>
          <div className="grow">
            
            {children}
            
            
          </div>
          
        </main>
        
      </body>
    </html>
  );
}
